version: '3.8'

services:
    # Laravel Application (PHP-FPM)
    app:
        image: webdevops/php-nginx:8.4
        container_name: laravel_app
        restart: always
        working_dir: /app
        environment:
            WEB_DOCUMENT_ROOT: /app/public
            TZ: Europe/Berlin
        volumes:
            - ./:/app
        networks:
            - hof-internal
            - galaxy-network-storage
    # Redis for cache and queue backend
    redis:
        image: redis:alpine
        container_name: laravel_redis
        restart: always
        networks:
            - hof-internal

    # Queue worker managed by supervisord
    worker:
        build:
            context: .
            dockerfile: Dockerfile.worker
        container_name: laravel_queue_worker
        restart: always
        depends_on:
            - redis
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./supervisord.conf:/etc/supervisor/conf.d/worker.conf:ro
        command: ["supervisord", "-c", "/etc/supervisor/conf.d/worker.conf", "-n"]
        networks:
            - hof-internal
            - galaxy-network-storage
    # Nginx HTTP server
    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: always
        depends_on:
            - app
        volumes:
            - ./:/var/www/html:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        networks:
            - hof-internal
            - proxy

# Networks definition
networks:
    # Internal network for app, redis, worker, nginx
    hof-internal:
        driver: bridge
    galaxy-network-storage:
        external: true
    # External network for nginx proxy
    proxy:
        external: true
        name: proxy
